export interface Product {
    id: string;
    name: string;
    type: string;
    description: string;
    price: number;
    colour: string;
    path: string;
}

const BASE_URL = "https://rmcnjxvjosmglbobgfyh.supabase.co/storage/v1/object/public/products/";

export const products: Product[] = [
    {
        id: "1",
        name: "Watch",
        type: "jewelry",
        description: "A stylish watch with a leather strap",
        price: 29.99,
        colour: "blue",
        path: `${BASE_URL}IMG-20260307-WA0088.jpg`,
    },
    {
        id: "2",
        name: "Shoes",
        type: "footwear",
        description: "Comfortable running shoes for everyday wear",
        price: 49.99,
        colour: "red",
        path: `${BASE_URL}IMG-20260307-WA0089.jpg`,
    },
    {
        id: "69",
        name: "La Vida es Bella",
        type: "perfume",
        description: "La Vie Est Belle perfume",
        price: 210000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0001.jpg`,
    },
    {
        id: "70",
        name: "Maison Crivelli's Oud Maracuja",
        type: "perfume",
        description: "Maison Crivelli's Oud Maracuja is a bold, fruity-woody Extrait de Parfum (2023) blending bright passion fruit with intense, smoky oud and leather. 100ml",
        price: 480000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0002.jpg`,
    },
    {
        id: "73",
        name: "9pm Elixir Afnan",
        type: "perfume",
        description: "9pm Elixir by Afnan perfume",
        price: 135000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0005.jpg`,
    },
    {
        id: "74",
        name: "Asad Elixir Lattafa",
        type: "perfume",
        description: "Asad Elixir by Lattafa perfume",
        price: 75000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0006.jpg`,
    },
    {
        id: "75",
        name: "Hayaati Lattafa",
        type: "perfume",
        description: "Hayaati by Lattafa perfume",
        price: 25000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0007.jpg`,
    },
    {
        id: "76",
        name: "Teriaq Intense Lattafa",
        type: "perfume",
        description: "Teriaq Intense by Lattafa perfume",
        price: 87000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0008.jpg`,
    },
    {
        id: "79",
        name: "His Coffession Lattafa",
        type: "perfume",
        description: "His Coffession by Lattafa perfume",
        price: 63000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0009.jpg`,
    },
    {
        id: "80",
        name: "Haramain Amber Oud",
        type: "perfume",
        description: "Haramain Amber Oud perfume",
        price: 185000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0010.jpg`,
    },
    {
        id: "82",
        name: "Tom Ford Lost Cherry",
        type: "perfume",
        description: "Tom Ford Lost Cherry - rich blend of black cherry, almond, and spicy Turkish rose. 100ml",
        price: 650000,
        colour: "brown",
        path: `${BASE_URL}IMG-20260401-WA0012.jpg`,
    },
    {
        id: "83",
        name: "Maison Extrait de Parfum",
        type: "perfume",
        description: "Barakkat Rouge 540, 100ml, 3.4 FLOZ",
        price: 29500,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0013.jpg`,
    },
    {
        id: "84",
        name: "Christian Dior Oud Ispahan",
        type: "perfume",
        description: "Christian Dior Oud Ispahan 100ml - opulent, unisex oriental floral fragrance with Damascena rose and intense agarwood (oud).",
        price: 1400000,
        colour: "gold",
        path: `${BASE_URL}IMG-20260401-WA0014.jpg`,
    },
    {
        id: "85",
        name: "La Vie Est Belle",
        type: "perfume",
        description: "La Vie Est Belle perfume, 75ml, 2.5 FLOZ",
        price: 50000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0015.jpg`,
    },
    {
        id: "86",
        name: "Dolce & Gabbana",
        type: "perfume",
        description: "Dolce & Gabbana Rose The One perfume",
        price: 200000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0016.jpg`,
    },
    {
        id: "87",
        name: "Tom Ford Tobacco Vanille",
        type: "perfume",
        description: "Tom Ford Tobacco Vanille 100ml Eau de Parfum - luxurious unisex Oriental Spicy fragrance with tobacco leaf, tonka bean, vanilla, and cocoa.",
        price: 550000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0017.jpg`,
    },
    {
        id: "88",
        name: "Maison Fragrance Khurshid Paris",
        type: "perfume",
        description: "Oceanic Rouge 504, Eau de Parfum",
        price: 20000,
        colour: "brown",
        path: `${BASE_URL}IMG-20260401-WA0019.jpg`,
    },
    {
        id: "89",
        name: "Club de Nuit",
        type: "perfume",
        description: "Club de Nuit perfume, 105ml",
        price: 70000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0020.jpg`,
    },
    {
        id: "90",
        name: "Body Mist",
        type: "perfume",
        description: "Body mist perfume",
        price: 15000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0021.jpg`,
    },
    {
        id: "91",
        name: "Gucci Osmanthus",
        type: "perfume",
        description: "Gucci Osmanthus - high-end floral-woody unisex scent with osmanthus flower, apricot, and sandalwood. 100ml",
        price: 580000,
        colour: "chocolate",
        path: `${BASE_URL}IMG-20260401-WA0022.jpg`,
    },
    {
        id: "92",
        name: "Bloom",
        type: "perfume",
        description: "G.M.C Maria Grazia Cucinotta Bloom, 100ml, 3.4 FLOZ",
        price: 45000,
        colour: "green",
        path: `${BASE_URL}IMG-20260401-WA0023.jpg`,
    },
    {
        id: "93",
        name: "Roja Perfume Burlington",
        type: "perfume",
        description: "Roja Perfume Burlington 19 review",
        price: 450000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0024.jpg`,
    },
    {
        id: "94",
        name: "Viktor & Rolf Flowerbomb",
        type: "perfume",
        description: "Viktor & Rolf Flowerbomb Crystal",
        price: 70000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0025.jpg`,
    },
    {
        id: "95",
        name: "Marc Jacobs Pour Homme",
        type: "perfume",
        description: "Marc Jacobs Pour Homme - 100ml, Eau de Parfum",
        price: 18000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0026.jpg`,
    },
    {
        id: "96",
        name: "Euphoric",
        type: "perfume",
        description: "Euphoric perfume",
        price: 60000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0027.jpg`,
    },
    {
        id: "97",
        name: "Terre d'Hermes",
        type: "perfume",
        description: "Terre d'Hermes - Eau de Parfum natural spray",
        price: 40000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0028.jpg`,
    },
    {
        id: "98",
        name: "Bleu de Chanel",
        type: "perfume",
        description: "Bleu de Chanel perfume",
        price: 15000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0029.jpg`,
    },
    {
        id: "99",
        name: "Azzaro The Most Wanted",
        type: "perfume",
        description: "Azzaro The Most Wanted perfume",
        price: 180000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0030.jpg`,
    },
    {
        id: "100",
        name: "Dior Sauvage",
        type: "perfume",
        description: "Dior Sauvage - Eau de Parfum, 100ml, 3.4 FLOZ",
        price: 120000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0031.jpg`,
    },
    {
        id: "104",
        name: "Ombre Nomade Louis Vuitton",
        type: "perfume",
        description: "Louis Vuitton Ombre Nomade - Assam Oud wood, benzoin, raspberry, and leathery notes. Smoky, fruity, and sweet.",
        price: 1000000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0032.jpg`,
    },
    {
        id: "105",
        name: "Gabrielle Chanel",
        type: "perfume",
        description: "Gabrielle Chanel perfume",
        price: 30000,
        colour: "gold",
        path: `${BASE_URL}IMG-20260401-WA0033.jpg`,
    },
    {
        id: "106",
        name: "Libre Eau de Parfum",
        type: "perfume",
        description: "Libre Eau de Parfum",
        price: 60000,
        colour: "gold",
        path: `${BASE_URL}IMG-20260401-WA0034.jpg`,
    },
    {
        id: "107",
        name: "Bloom",
        type: "perfume",
        description: "G.M.C Maria Grazia Cucinotta Bloom, 100ml, 3.4 FLOZ",
        price: 50000,
        colour: "red",
        path: `${BASE_URL}IMG-20260401-WA0035.jpg`,
    },
    {
        id: "108",
        name: "Sexy Scandal",
        type: "perfume",
        description: "Sexy Scandal perfume",
        price: 22000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0036.jpg`,
    },
    {
        id: "109",
        name: "Gabrielle Chanel",
        type: "perfume",
        description: "Gabrielle Chanel - solar and voluptuous feminine fragrance by Olivier Polge. 100ml",
        price: 390000,
        colour: "gold",
        path: `${BASE_URL}IMG-20260401-WA0037.jpg`,
    },
    {
        id: "110",
        name: "Angels Share Kilian",
        type: "perfume",
        description: "Kilian Angels Share - vaporisation spray, 50ml, 1.7 oz",
        price: 430000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0038.jpg`,
    },
    {
        id: "111",
        name: "Pure Oud Louis Vuitton",
        type: "perfume",
        description: "Louis Vuitton Pure Oud - ultra-premium unisex woody-spicy fragrance with rare Indian and Cambodian oud. 100ml",
        price: 4000000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0039.jpg`,
    },
    {
        id: "112",
        name: "Coco Mademoiselle",
        type: "perfume",
        description: "Coco Mademoiselle perfume",
        price: 15000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0040.jpg`,
    },
    {
        id: "113",
        name: "Dior Sauvage Elixir",
        type: "perfume",
        description: "Dior Sauvage Elixir - intensely concentrated woody-aromatic fragrance with lavender, spices, and rich woods. 10-12+ hours longevity.",
        price: 420000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0041.jpg`,
    },
    {
        id: "114",
        name: "5th Avenue Coach",
        type: "perfume",
        description: "5th Avenue Coach - Eau de Parfum",
        price: 20000,
        colour: "gold",
        path: `${BASE_URL}IMG-20260401-WA0042.jpg`,
    },
    {
        id: "115",
        name: "Coach Eau de Parfum",
        type: "perfume",
        description: "Coach Eau de Parfum spray, 100ml, 3.4 FLOZ",
        price: 42000,
        colour: "black",
        path: `${BASE_URL}IMG-20260401-WA0043.jpg`,
    },
];
